# Generated by Django 2.1.7 on 2019-03-07 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaboration', related_query_name='created_collaborations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_collaboration', related_query_name='modified_collaborations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_collaboration', related_query_name='owned_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultilangField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_multilangfield', related_query_name='created_multilangfields', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_multilangfield', related_query_name='modified_multilangfields', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_multilangfield', related_query_name='owned_multilangfields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultilangFieldEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('lang', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_multilangfieldentry', related_query_name='created_multilangfieldentrys', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', related_query_name='entry', to='backend.MultilangField')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_multilangfieldentry', related_query_name='modified_multilangfieldentrys', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_multilangfieldentry', related_query_name='owned_multilangfieldentrys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Multilanguage entries',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=254)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project', related_query_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(related_name='managed_projects', related_query_name='managed_project', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_project', related_query_name='modified_projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_project', related_query_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=254)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_structure', related_query_name='created_structures', to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(related_name='managed_structures', related_query_name='managed_structure', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_structure', related_query_name='modified_structures', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_structure', related_query_name='owned_structures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='collaboration',
            name='partners',
            field=models.ManyToManyField(related_name='partner_collaborations', related_query_name='partner_collaboration', to='backend.Structure'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', related_query_name='collaboration', to='backend.Project'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', related_query_name='collaboration', to='backend.Structure'),
        ),
    ]
