# Generated by Django 2.1.7 on 2019-03-07 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190307_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='partnerships', related_query_name='partnership', to='backend.Structure'),
        ),
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_projects', related_query_name='managed_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structure',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_structures', related_query_name='managed_structure', to=settings.AUTH_USER_MODEL),
        ),
    ]
