# Generated by Django 2.1.7 on 2019-03-07 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190308_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='researchers',
            field=models.ManyToManyField(blank=True, related_name='researched_projects', related_query_name='researched_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration', related_query_name='collaboration', to='backend.Project'),
        ),
    ]
