# Generated by Django 2.1.7 on 2019-03-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190308_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='projects', related_query_name='project', to='backend.Keyword'),
        ),
    ]
