# Generated by Django 2.1.7 on 2019-03-16 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_project_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='researchers',
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaborations', related_query_name='created_collaboration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_collaborations', related_query_name='modified_collaboration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_collaborations', related_query_name='owned_collaboration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='multilangfield',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_multilangfields', related_query_name='created_multilangfield', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='multilangfield',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_multilangfields', related_query_name='modified_multilangfield', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='multilangfield',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_multilangfields', related_query_name='owned_multilangfield', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='multilangfieldentry',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_multilangfieldentrys', related_query_name='created_multilangfieldentry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='multilangfieldentry',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_multilangfieldentrys', related_query_name='modified_multilangfieldentry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='multilangfieldentry',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_multilangfieldentrys', related_query_name='owned_multilangfieldentry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', related_query_name='created_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_projects', related_query_name='modified_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', related_query_name='owned_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structure',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_structures', related_query_name='created_structure', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structure',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_structures', related_query_name='modified_structure', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structure',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_structures', related_query_name='owned_structure', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', related_query_name='created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_users', related_query_name='modified_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_users', related_query_name='owned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Project'),
        ),
        migrations.AddField(
            model_name='participation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ParticipationRole'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='researched_projects', related_query_name='researched_project', through='backend.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
