# Generated by Django 2.1.7 on 2019-03-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_participation'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.KnowledgeArea')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='acronym',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('research', 'Research'), ('publicEngagement', 'Public Engagement'), ('serviceLearning', 'Service Learning')], max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='related_projects',
            field=models.ManyToManyField(blank=True, to='backend.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'project')},
        ),
        migrations.AddField(
            model_name='project',
            name='knowledge_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.KnowledgeArea'),
        ),
    ]
