# Generated by Django 2.1.7 on 2019-03-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_expand_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='structure',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='structure',
            name='contact_postal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='contact_social_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='contact_social_other',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='contact_social_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='contact_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='knowledge_areas',
            field=models.ManyToManyField(blank=True, to='backend.KnowledgeArea'),
        ),
        migrations.AddField(
            model_name='structure',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='year_founded',
            field=models.PositiveIntegerField(default=1900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='projects', related_query_name='project', to='backend.Network'),
        ),
    ]
