# Generated by Django 2.1.7 on 2019-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_structure_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='structure',
            name='image_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='structure',
            name='contact_social_facebook',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='structure',
            name='contact_social_other',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='structure',
            name='contact_social_twitter',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='structure',
            name='contact_website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
