# Generated by Django 2.1.7 on 2019-03-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_structurevalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='structure',
            name='validation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure', related_query_name='structure', to='backend.StructureValidation'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='year_founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
