# Generated by Django 2.1.7 on 2019-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
