# Generated by Django 2.1.7 on 2019-04-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAtPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('name', models.CharField(max_length=254)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='projectatphase',
            name='project_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ProjectPhase'),
        ),
        migrations.AddField(
            model_name='project',
            name='phases',
            field=models.ManyToManyField(blank=True, through='backend.ProjectAtPhase', to='backend.ProjectPhase'),
        ),
    ]
