# Generated by Django 2.1.7 on 2019-04-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_project-phase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectphase',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='projectatphase',
            unique_together={('project', 'project_phase')},
        ),
    ]
