# Generated by Django 2.1.7 on 2019-04-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_evaluation-answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['key']},
        ),
        migrations.AddField(
            model_name='response',
            name='answer_multiple',
            field=models.ManyToManyField(blank=True, to='backend.Answer'),
        ),
        migrations.AlterField(
            model_name='response',
            name='answer_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_answers', related_query_name='single_answer', to='backend.Answer'),
        ),
    ]
