# Generated by Django 2.1.7 on 2019-04-08 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_response-multiple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilangfield',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='multilangfield',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='multilangfield',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='multilangfieldentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='multilangfieldentry',
            name='field',
        ),
        migrations.RemoveField(
            model_name='multilangfieldentry',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='multilangfieldentry',
            name='owner',
        ),
        migrations.AddField(
            model_name='participation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participation',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_participations', related_query_name='created_participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_participations', related_query_name='modified_participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participation',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_participations', related_query_name='owned_participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectatphase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectatphase',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projectatphases', related_query_name='created_projectatphase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectatphase',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projectatphase',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_projectatphases', related_query_name='modified_projectatphase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectatphase',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projectatphases', related_query_name='owned_projectatphase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('participation', 'phase')},
        ),
        migrations.DeleteModel(
            name='MultilangField',
        ),
        migrations.DeleteModel(
            name='MultilangFieldEntry',
        ),
    ]
