# Generated by Django 2.2 on 2019-04-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='participation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Participation'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ProjectAtPhase'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, to='backend.Answer'),
        ),
        migrations.AlterField(
            model_name='response',
            name='answer_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_answers', related_query_name='single_answer', to='backend.Answer'),
        ),
        migrations.AlterField(
            model_name='response',
            name='evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Evaluation'),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('evaluation', 'question')},
        ),
    ]
