# Generated by Django 2.2 on 2019-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_postal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_social_facebook',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_social_other',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_social_twitter',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='country_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='structure',
            name='country_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Teriary (Labor market)'), ('DEGREE', 'Bachelors or Degree'), ('MASTER', 'Masters'), ('DOCTORAL', 'Doctoral')], max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('RESEARCH', 'Research'), ('PARTICIPATORY_RESEARCH', 'Participatory Research'), ('PARTICIPATORY_ACTION_RESEARCH', 'Participatory Action Research'), ('CITIZEN_SCIENCE', 'Citizen Science'), ('PUBLIC_ENGAGEMENT', 'Public Engagement'), ('SERVICE_LEARNING', 'Service Learning'), ('ADVOCACY', 'Advocacy'), ('INNOVATION', 'Innovation'), ('POLICY_INNOVATION', 'Policy Innovation'), ('OTHER', 'Other')], max_length=128),
        ),
    ]
