# Generated by Django 2.2 on 2019-05-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='validation',
        ),
        migrations.AddField(
            model_name='structurevalidation',
            name='structure',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='backend.Structure'),
        ),
        migrations.AlterField(
            model_name='structurevalidation',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
