# Generated by Django 2.2 on 2019-05-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_structure_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('MULTIPLE', 'Multiple Choice'), ('DEGREE', 'Degree'), ('TEXT', 'Text')], max_length=32),
        ),
    ]
