# Generated by Django 2.2 on 2020-11-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_eval_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='i18n',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
