# Generated by Django 2.2 on 2020-11-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_question_i18n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['answer_type', 'id']},
        ),
    ]
