# Generated by Django 2.2 on 2020-11-10 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_question_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('HELP', 'Help Article'), ('NEWS', 'News Article'), ('BLOG', 'Blog Post')], max_length=64)),
                ('name', models.CharField(help_text='Internal use only. Create a name that identifies the content you will create.', max_length=512, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contentmasters', related_query_name='created_contentmaster', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_contentmasters', related_query_name='modified_contentmaster', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contentmasters', related_query_name='owned_contentmaster', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('topic', models.CharField(help_text='Define what this Article is about. Use single words and re-use them across articles.', max_length=64)),
                ('title', models.CharField(help_text='Keep it short.', max_length=512)),
                ('slug', models.SlugField(blank=True, help_text='Autogenerated.', unique=True)),
                ('summary', models.TextField(max_length=1024)),
                ('body', models.TextField(help_text='Full MarkDown enabled.')),
                ('locale', models.CharField(choices=[('ar', 'Arabic'), ('ca', 'Catalan'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hu', 'Hungarian'), ('it', 'Italian'), ('nl', 'Dutch')], max_length=5)),
                ('published', models.BooleanField(default=False, help_text='Check this box if the article is ready to be public.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contents', related_query_name='created_content', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ContentMaster')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_contents', related_query_name='modified_content', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of the instance. This user will be able to edit the            instance or even delete it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contents', related_query_name='owned_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('master', 'locale')},
            },
        ),
    ]
