# Generated by Django 2.2 on 2020-12-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_user_eval_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_realname',
            field=models.BooleanField(default=False),
        ),
    ]
