# Generated by Django 2.2 on 2020-12-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_user_hide_realname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary (Labor market)'), ('DEGREE', 'Bachelors or Degree'), ('MASTER', 'Masters'), ('DOCTORAL', 'Doctoral')], max_length=128),
        ),
    ]
