# Generated by Django 2.2 on 2021-01-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(help_text="Article title. Will be used for the URL slug (i.e. '/help/article-slug') So write something useful and concise.", max_length=512),
        ),
    ]
