# Generated by Django 2.2 on 2021-01-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_attachment_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='response',
            name='answer_text',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
