# Generated by Django 2.2 on 2021-02-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_response_longertext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmaster',
            options={'ordering': ['sorting']},
        ),
        migrations.AddField(
            model_name='contentmaster',
            name='sorting',
            field=models.PositiveIntegerField(default=1, help_text='Sorting priority of this content. Lower numbers will be shown first.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='eval_version',
            field=models.IntegerField(default=2),
        ),
    ]
