# Generated by Django 2.2 on 2021-03-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_contentmaster_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='locale',
            field=models.CharField(choices=[('ar', 'Arabic'), ('ca', 'Catalan'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hu', 'Hungarian'), ('it', 'Italian'), ('nl', 'Dutch'), ('pt', 'Portuguese')], max_length=5),
        ),
    ]
