# Generated by Django 2.2 on 2021-03-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_content_pt_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmaster',
            name='extra_style',
            field=models.CharField(blank=True, choices=[('', 'No extra styles'), ('grid', 'Striped Tables with header'), ('orange', 'Orange theme'), ('green', 'Green theme'), ('yellow', 'Yellow theme')], default='', max_length=128),
        ),
    ]
