# Generated by Django 2.2 on 2021-03-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_contentmaster_extra_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmaster',
            name='extra_style',
            field=models.CharField(blank=True, choices=[('', 'No extra styles'), ('grid', 'Striped Tables with header'), ('orange-theme', 'Orange theme'), ('green-theme', 'Green theme'), ('yellow-theme', 'Yellow theme'), ('white-theme', 'White theme')], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='country_code',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
