# Generated by Django 2.2 on 2021-04-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_project_countrycodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='country_code',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
