# Generated by Django 2.2 on 2021-04-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_structure_countrycodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmaster',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ContentMaster'),
        ),
        migrations.AlterField(
            model_name='contentmaster',
            name='type',
            field=models.CharField(choices=[('HELP', 'Help Article'), ('NEWS', 'News Article'), ('BLOG', 'Blog Post'), ('COURSE', 'Course'), ('MODULE', 'Course Module')], max_length=64),
        ),
    ]
