# Generated by Django 2.2 on 2021-05-06 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0045_content_course_modules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="body",
            field=models.TextField(blank=True, help_text="Full MarkDown enabled."),
        ),
        migrations.AlterField(
            model_name="content",
            name="summary",
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
