# Generated by Django 2.2 on 2021-05-08 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0046_content_optional_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="structure",
            name="networks",
            field=models.ManyToManyField(
                blank=True,
                related_name="structures",
                related_query_name="structure",
                to="backend.Network",
            ),
        ),
    ]
