# Generated by Django 2.2 on 2021-05-14 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0047_structure_networks"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="content",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contentmaster",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participation",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectatphase",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="response",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="structure",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="structurevalidation",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_attachments",
                related_query_name="owned_attachment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_collaborations",
                related_query_name="owned_collaboration",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_contents",
                related_query_name="owned_content",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contentmaster",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_contentmasters",
                related_query_name="owned_contentmaster",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_evaluations",
                related_query_name="owned_evaluation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_participations",
                related_query_name="owned_participation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_projects",
                related_query_name="owned_project",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectatphase",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_projectatphases",
                related_query_name="owned_projectatphase",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_responses",
                related_query_name="owned_response",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_structures",
                related_query_name="owned_structure",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="structurevalidation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_structurevalidations",
                related_query_name="owned_structurevalidation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the instance. This user will be able to edit the            instance or even delete it. Leave empty to set yourself as owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_users",
                related_query_name="owned_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
