# Generated by Django 2.2 on 2021-06-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_contentmaster_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmaster',
            name='image_url',
            field=models.URLField(blank=True, help_text="For courses, the Image shown on the course list. For Course Modules, the Cover image shown on the module's content page.", max_length=500),
        ),
        migrations.AlterField(
            model_name='contentmaster',
            name='theme_color',
            field=models.CharField(default='white', help_text='For Course Modules, the theme color of this module.', max_length=128),
        ),
    ]
