# Generated by Django 2.2 on 2021-06-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=models.TextField(blank=True, max_length=4096),
        ),
    ]
